# Generated by Django 5.2.3 on 2025-06-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datainsertapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datas',
            new_name='Data',
        ),
    ]
